// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Frozen        int64                  `protobuf:"varint,2,opt,name=frozen,proto3" json:"frozen,omitempty"`
	Available     int64                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetFrozen() int64 {
	if x != nil {
		return x.Frozen
	}
	return 0
}

func (x *GetBalanceResponse) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type PreAuthRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceName      string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	RequestId        string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	EstimatedCredits int64                  `protobuf:"varint,4,opt,name=estimated_credits,json=estimatedCredits,proto3" json:"estimated_credits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PreAuthRequest) Reset() {
	*x = PreAuthRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreAuthRequest) ProtoMessage() {}

func (x *PreAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreAuthRequest.ProtoReflect.Descriptor instead.
func (*PreAuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *PreAuthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PreAuthRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PreAuthRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PreAuthRequest) GetEstimatedCredits() int64 {
	if x != nil {
		return x.EstimatedCredits
	}
	return 0
}

type PreAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        string                 `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	FrozenCredits int64                  `protobuf:"varint,2,opt,name=frozen_credits,json=frozenCredits,proto3" json:"frozen_credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreAuthResponse) Reset() {
	*x = PreAuthResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreAuthResponse) ProtoMessage() {}

func (x *PreAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreAuthResponse.ProtoReflect.Descriptor instead.
func (*PreAuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *PreAuthResponse) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *PreAuthResponse) GetFrozenCredits() int64 {
	if x != nil {
		return x.FrozenCredits
	}
	return 0
}

type SettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        string                 `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	ActualCredits int64                  `protobuf:"varint,2,opt,name=actual_credits,json=actualCredits,proto3" json:"actual_credits,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRequest) Reset() {
	*x = SettleRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequest) ProtoMessage() {}

func (x *SettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequest.ProtoReflect.Descriptor instead.
func (*SettleRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *SettleRequest) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *SettleRequest) GetActualCredits() int64 {
	if x != nil {
		return x.ActualCredits
	}
	return 0
}

func (x *SettleRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SettleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SettleRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SettleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleResponse) Reset() {
	*x = SettleResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleResponse) ProtoMessage() {}

func (x *SettleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleResponse.ProtoReflect.Descriptor instead.
func (*SettleResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *SettleResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        string                 `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{8}
}

func (x *RollbackRequest) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{9}
}

func (x *RollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IssueGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Credits       int64                  `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	TtlDays       int64                  `protobuf:"varint,4,opt,name=ttl_days,json=ttlDays,proto3" json:"ttl_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueGrantRequest) Reset() {
	*x = IssueGrantRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueGrantRequest) ProtoMessage() {}

func (x *IssueGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueGrantRequest.ProtoReflect.Descriptor instead.
func (*IssueGrantRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{10}
}

func (x *IssueGrantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IssueGrantRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IssueGrantRequest) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *IssueGrantRequest) GetTtlDays() int64 {
	if x != nil {
		return x.TtlDays
	}
	return 0
}

type IssueGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueGrantResponse) Reset() {
	*x = IssueGrantResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueGrantResponse) ProtoMessage() {}

func (x *IssueGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueGrantResponse.ProtoReflect.Descriptor instead.
func (*IssueGrantResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{11}
}

func (x *IssueGrantResponse) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *IssueGrantResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

var File_proto_billing_v1_billing_proto protoreflect.FileDescriptor

const file_proto_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/billing/v1/billing.proto\x12\n" +
	"billing.v1\".\n" +
	"\x13CreateWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x14CreateWalletResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"d\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\x12\x16\n" +
	"\x06frozen\x18\x02 \x01(\x03R\x06frozen\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x03R\tavailable\"\x98\x01\n" +
	"\x0ePreAuthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12+\n" +
	"\x11estimated_credits\x18\x04 \x01(\x03R\x10estimatedCredits\"Q\n" +
	"\x0fPreAuthResponse\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\x12%\n" +
	"\x0efrozen_credits\x18\x02 \x01(\x03R\rfrozenCredits\"\xb3\x01\n" +
	"\rSettleRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\x12%\n" +
	"\x0eactual_credits\x18\x02 \x01(\x03R\ractualCredits\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"7\n" +
	"\x0eSettleResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"*\n" +
	"\x0fRollbackRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\",\n" +
	"\x10RollbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"u\n" +
	"\x11IssueGrantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acredits\x18\x03 \x01(\x03R\acredits\x12\x19\n" +
	"\bttl_days\x18\x04 \x01(\x03R\attlDays\"V\n" +
	"\x12IssueGrantResponse\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId2\xc9\x03\n" +
	"\x0eBillingService\x12Q\n" +
	"\fCreateWallet\x12\x1f.billing.v1.CreateWalletRequest\x1a .billing.v1.CreateWalletResponse\x12K\n" +
	"\n" +
	"GetBalance\x12\x1d.billing.v1.GetBalanceRequest\x1a\x1e.billing.v1.GetBalanceResponse\x12B\n" +
	"\aPreAuth\x12\x1a.billing.v1.PreAuthRequest\x1a\x1b.billing.v1.PreAuthResponse\x12?\n" +
	"\x06Settle\x12\x19.billing.v1.SettleRequest\x1a\x1a.billing.v1.SettleResponse\x12E\n" +
	"\bRollback\x12\x1b.billing.v1.RollbackRequest\x1a\x1c.billing.v1.RollbackResponse\x12K\n" +
	"\n" +
	"IssueGrant\x12\x1d.billing.v1.IssueGrantRequest\x1a\x1e.billing.v1.IssueGrantResponseBLZJgithub.com/Leelaobai/ai-resume/services/billing/proto/billing/v1;billingv1b\x06proto3"

var (
	file_proto_billing_v1_billing_proto_rawDescOnce sync.Once
	file_proto_billing_v1_billing_proto_rawDescData []byte
)

func file_proto_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_billing_v1_billing_proto_rawDesc), len(file_proto_billing_v1_billing_proto_rawDesc)))
	})
	return file_proto_billing_v1_billing_proto_rawDescData
}

var file_proto_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_billing_v1_billing_proto_goTypes = []any{
	(*CreateWalletRequest)(nil),  // 0: billing.v1.CreateWalletRequest
	(*CreateWalletResponse)(nil), // 1: billing.v1.CreateWalletResponse
	(*GetBalanceRequest)(nil),    // 2: billing.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),   // 3: billing.v1.GetBalanceResponse
	(*PreAuthRequest)(nil),       // 4: billing.v1.PreAuthRequest
	(*PreAuthResponse)(nil),      // 5: billing.v1.PreAuthResponse
	(*SettleRequest)(nil),        // 6: billing.v1.SettleRequest
	(*SettleResponse)(nil),       // 7: billing.v1.SettleResponse
	(*RollbackRequest)(nil),      // 8: billing.v1.RollbackRequest
	(*RollbackResponse)(nil),     // 9: billing.v1.RollbackResponse
	(*IssueGrantRequest)(nil),    // 10: billing.v1.IssueGrantRequest
	(*IssueGrantResponse)(nil),   // 11: billing.v1.IssueGrantResponse
}
var file_proto_billing_v1_billing_proto_depIdxs = []int32{
	0,  // 0: billing.v1.BillingService.CreateWallet:input_type -> billing.v1.CreateWalletRequest
	2,  // 1: billing.v1.BillingService.GetBalance:input_type -> billing.v1.GetBalanceRequest
	4,  // 2: billing.v1.BillingService.PreAuth:input_type -> billing.v1.PreAuthRequest
	6,  // 3: billing.v1.BillingService.Settle:input_type -> billing.v1.SettleRequest
	8,  // 4: billing.v1.BillingService.Rollback:input_type -> billing.v1.RollbackRequest
	10, // 5: billing.v1.BillingService.IssueGrant:input_type -> billing.v1.IssueGrantRequest
	1,  // 6: billing.v1.BillingService.CreateWallet:output_type -> billing.v1.CreateWalletResponse
	3,  // 7: billing.v1.BillingService.GetBalance:output_type -> billing.v1.GetBalanceResponse
	5,  // 8: billing.v1.BillingService.PreAuth:output_type -> billing.v1.PreAuthResponse
	7,  // 9: billing.v1.BillingService.Settle:output_type -> billing.v1.SettleResponse
	9,  // 10: billing.v1.BillingService.Rollback:output_type -> billing.v1.RollbackResponse
	11, // 11: billing.v1.BillingService.IssueGrant:output_type -> billing.v1.IssueGrantResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_billing_v1_billing_proto_init() }
func file_proto_billing_v1_billing_proto_init() {
	if File_proto_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_billing_v1_billing_proto_rawDesc), len(file_proto_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_proto_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_v1_billing_proto = out.File
	file_proto_billing_v1_billing_proto_goTypes = nil
	file_proto_billing_v1_billing_proto_depIdxs = nil
}
